export const STATUS_ORDER = [
  'N','SN','PU','SS','MR','D','B','1','2','3','NS','SV','S','5','T','SI','C','P','E','X','G','J','U','L','CM'
]

export const STATUS_LABELS: Record<string, string> = {
  N:   'New',
  SN:  'Scope Needed',
  PU:  'Scope / Pickup Check',
  SS:  'Scope Scheduled',
  MR:  'Scope Complete / In Review',
  D:   'Waiting HOA Approval',
  B:   'Rel To Production',
  '1': 'Order Materials',
  '2': 'Materials Ordered',
  '3': 'Awaiting Parts',
  NS:  'Need to Schedule',
  SV:  'Need Schedule Service',
  S:   'Scheduled',
  '5': 'In Progress',
  T:   'Installed & Unpaid',
  SI:  'Need Subcontractor Invoice',
  C:   'Complete (Paid and Closed)',
  P:   'Installed & Paid',
  E:   'Cancel In Rescission',
  X:   'Cancel After Rescission',
  G:   'Cancelled By Mgt',
  J:   'Credit Decline',
  U:   'Unknown',
  L:   'Legal',
  CM:  'Commercial',
}

export const TAB_LABELS: Record<string, string> = {
  N:   'New',
  SN:  'Scope Needed',
  PU:  'Pickup Check',
  SS:  'Scope Scheduled',
  MR:  'In Review',
  D:   'Waiting HOA',
  B:   'Rel To Production',
  '1': 'Order Materials',
  '2': 'Materials Ordered',
  '3': 'Awaiting Parts',
  NS:  'Need to Schedule',
  SV:  'Need Svc Schedule',
  S:   'Scheduled',
  '5': 'In Progress',
  T:   'Installed & Unpaid',
  SI:  'Sub Invoice Needed',
  C:   'Complete',
  P:   'Installed & Paid',
  E:   'Cancel Rescission',
  X:   'Cancelled',
  G:   'Cancelled By Mgt',
  J:   'Credit Decline',
  U:   'Unknown',
  L:   'Legal',
  CM:  'Commercial',
}

export const STATUS_BADGE_COLOR: Record<string, string> = {
  N:   '#EEEDFE', SN: '#EEEDFE', PU: '#EEEDFE', SS: '#EEEDFE', MR: '#EEEDFE',
  D:   '#FAEEDA', B: '#FAEEDA', '3': '#FAEEDA',
  '1': '#E1F5EE', '2': '#E1F5EE', CM: '#E1F5EE',
  NS:  '#E6F1FB', SV: '#E6F1FB', S: '#E6F1FB', '5': '#E6F1FB',
  T:   '#FCEBEB', SI: '#FCEBEB',
  C:   '#E8F5E9', P: '#E8F5E9',
  E:   '#F0F0F0', X: '#F0F0F0', G: '#F0F0F0',
  J:   '#FDE8E8', L: '#FDE8E8',
  U:   '#F5F5F5',
}

export const STATUS_BADGE_TEXT: Record<string, string> = {
  N:   '#534AB7', SN: '#534AB7', PU: '#534AB7', SS: '#534AB7', MR: '#534AB7',
  D:   '#854F0B', B: '#854F0B', '3': '#854F0B',
  '1': '#0F6E56', '2': '#0F6E56', CM: '#0F6E56',
  NS:  '#185FA5', SV: '#185FA5', S: '#185FA5', '5': '#185FA5',
  T:   '#A32D2D', SI: '#A32D2D',
  C:   '#1B5E20', P: '#1B5E20',
  E:   '#555555', X: '#555555', G: '#555555',
  J:   '#A32D2D', L: '#A32D2D',
  U:   '#555555',
}
